CREATE TABLE IF NOT EXISTS Keyword (
  id SERIAL PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES Company(id) ON DELETE CASCADE,
  keyword VARCHAR NOT NULL,
  is_auto_generated BOOLEAN DEFAULT FALSE,
  weight FLOAT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Hashtag (
  id SERIAL PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES Company(id) ON DELETE CASCADE,
  tag VARCHAR UNIQUE NOT NULL,
  is_auto_generated BOOLEAN DEFAULT FALSE,
  popularity_score FLOAT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS PostHashtag (
  post_id INTEGER NOT NULL REFERENCES ContentPost(id) ON DELETE CASCADE,
  hashtag_id INTEGER NOT NULL REFERENCES Hashtag(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, hashtag_id)
);

CREATE TABLE IF NOT EXISTS PostKeyword (
  post_id INTEGER NOT NULL REFERENCES ContentPost(id) ON DELETE CASCADE,
  keyword_id INTEGER NOT NULL REFERENCES Keyword(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, keyword_id)
);
